apiVersion: v2
name: tiphys
description: A High Level Helm Chart
type: application
version: 0.9.27
appVersion: 1.16.3

dependencies:
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
